package com.serverless.dal;

import com.amazonaws.services.dynamodbv2.AmazonDynamoDB;
import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.amazonaws.services.dynamodbv2.model.AttributeValue;
import org.apache.log4j.Logger;

import java.io.IOException;
import java.util.HashMap;
import java.util.List;

@DynamoDBTable(tableName = "DATA_TABLE_NAME")
public class SensorData {
    /*
    ID
    SensorId
    SensorSerial
    TimeStamp
    Data
     */
    private static final String DATA_TABLE_NAME = System.getenv("DATA_TABLE_NAME");
    private static DynamoDBAdapter db_adapter;
    private final AmazonDynamoDB client;

    private final DynamoDBMapper dataMapper;
    private Logger logger = Logger.getLogger(this.getClass());


    private String id;

    private String sensorId;
    private String sensorName = "";
    private String timeStamp;
    private String dataType;
    private double data;



    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return this.id;
    }
    public void setId(String id) {

        this.id = id;
    }


    @DynamoDBAttribute(attributeName = "sensorId")
    public String getSensorId() {
        return this.sensorId;
    }
    public void setSensorId(String sensorId) {
        this.sensorId = sensorId;
    }

    @DynamoDBAttribute(attributeName = "sensorName")
    public String getSensorName() {
        return this.sensorName;
    }
    public void setSensorName(String name) {
        this.sensorName = sensorName;
    }


    @DynamoDBAttribute(attributeName = "timeStamp")
    public String getTimeStamp() {
        return this.timeStamp;
    }
    public void setTimeStamp(String timeStamp) {
        this.timeStamp = timeStamp;
    }

    @DynamoDBAttribute(attributeName = "dataType")
    public String getDataType() {
        return this.dataType;
    }
    public void setDataType(String dataType) {
        this.dataType = dataType;
    }

    @DynamoDBAttribute(attributeName = "data")
    public double getData() {
        return this.data;
    }
    public void setData(double data) {
        this.data = data;
    }


    public SensorData(){
        DynamoDBMapperConfig mapperConfig = DynamoDBMapperConfig.builder()
                .withTableNameOverride(new DynamoDBMapperConfig.TableNameOverride(DATA_TABLE_NAME))
                .build();
        // get the db adapter
        this.db_adapter = DynamoDBAdapter.getInstance();
        this.client = this.db_adapter.getDbClient();
        // create the mapper with config
        this.dataMapper = this.db_adapter.createDbMapper(mapperConfig);


    }

    public void save(SensorData sensorData) throws IOException {
        logger.info("SensorData - save(): " + sensorData.toString());
        this.dataMapper.save(sensorData);

    }

    public SensorData get(String id) throws IOException {
        SensorData data = null;

        HashMap<String, AttributeValue> av = new HashMap<String, AttributeValue>();
        av.put(":v1", new AttributeValue().withS(id));

        DynamoDBQueryExpression<SensorData> queryExp = new DynamoDBQueryExpression<SensorData>()
                .withKeyConditionExpression("id = :v1")
                .withExpressionAttributeValues(av);

        PaginatedQueryList<SensorData> result = this.dataMapper.query(SensorData.class, queryExp);
        if (result.size() > 0) {
            data = result.get(0);
            logger.info("Sensor - get(): sensor - " + data.toString());
        } else {
            logger.info("Sensor - get(): sensor - Not Found.");
        }
        return data;
    }

    public Boolean delete(String id) throws IOException {
        SensorData data = null;

        // get product if exists
        data = get(id);
        if (data != null) {
            logger.info("Sensor Data - delete(): " + data.toString());
            this.dataMapper.delete(data);
        } else {
            logger.info("Sensor delete - delete(): data - does not exist.");
            return false;
        }
        return true;
    }


    public List<SensorData> getData(String sensorId, String sensorSerial) throws IOException {
        DynamoDBScanExpression scanExp = new DynamoDBScanExpression();
        List<SensorData> results = this.dataMapper.scan(SensorData.class, scanExp);
        for (SensorData data : results) {

            if(data.getId().equals(sensorId) || data.getSensorName().equals(sensorSerial)){
               continue;
            }

            if(!data.getId().equals(sensorId) && data.getSensorName() == null){
               results.remove(data);
            }else if(!data.getSensorName().equals(sensorSerial) && data.getId() == null){
                results.remove(data);
            }else if(!data.getSensorName().equals(sensorSerial) && !data.getId().equals(sensorId)){
                results.remove(data);
            }else if(data.getSensorName() == null && data.getId() == null){
                results.remove(data);
            }
        }
        return results;
    }
}
